### ISSUE TITLE
Virtual File Directory Does not use caching

### ISSUE THREAD

**Issue by TylerThompson** [bwhite000/web-server#4]
It would be an awesome feature to have caching for images, fonts, css and js that are in the virtual file directory, so we don't need to waste alot of bandwidth serving the same content everytime. Maybe comparing the time stamps of the files would serve as a good method for caching?

**Comment by bwhite000** [comment]
Hey Tyler- thanks for entering a GitHub issue after us talking about this yesterday! I'll work on coding this into the next release :)

**Comment by TylerThompson** [comment]
Woot woot:-)

**Comment by bwhite000** [comment]
Added this functionality to the new `serveStaticVirtualDirectory()` method in v2.0.0 using the `shouldPreCache: true` parameter. Enjoy!
