### ISSUE TITLE
Upgrade InternetAddress.LOOPBACK_IP_V4 to InternetAddress.ANY_IP_V4

### ISSUE THREAD

**Issue by TylerThompson** [bwhite000/web-server#5]
I think for the demo and in the package itself, we should change InternetAddress.LOOPBACK_IP_V4 to use any IP so people just starting out with the package don't get frustrated when putting this code on a production server to find out that they are not able to access the server from outside of said server. Changing it to any will provide this support to access said server.

**Comment by bwhite000** [comment]
Thanks again very much, Tyler, for opening an issue in GitHub and for your contribution to improving the project!! Your change idea has been included in the v2.0.0+3 released today, Mar. 5, 2016!

**Comment by bwhite000** [comment]
The repo tag for v2.0.0+3: https://github.com/bwhite000/web-server/releases/tag/v2.0.0%2B3

**Comment by TylerThompson** [comment]
Glad to be of help:)
